language: ruby
rvm:
- 2.2

before_script:
 - chmod +x ./scripts/cibuild.sh

script: ./scripts/cibuild.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production
