language: ruby
sudo: false

rvm:
- 2.3.1

addons:
  apt:
    packages:
      - sshpass

script: "./scripts/cibuild.sh"

deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/cideploy.sh"
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
