language: ruby
rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

before_script:
 - chmod +x ./scripts/cibuild.sh # or do this locally and commit
 - chmod +x ./scripts/cideploy.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/cideploy.sh
  on:
    branch: master
