# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaustav Das Modak
email: kaustav.dasmodak@gmail.com
description: "Kaustav's journal. An anecdote on research, programming, philosophy and what not."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaustavdm.in" # the base hostname & protocol for your site
twitter_username: kaustavdm
github_username:  kaustavdm

plugins:
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-feed

# Site settings
markdown: kramdown

kramdown:
  input: GFM

timezone: Asia/Kolkata

permalink: :slug.html

# Paginate
paginate: 7
paginate_path: "/page-:num/"

# Exclude
exclude: [scripts/, README.md, Gemfile, Gemfile.lock, vendor]

# Safe mode
safe: true

# Feed
feed:
  path: atom.xml

layouts_dir: _theme/_layouts
data_dir: _theme/_data
includes_dir: _theme/_includes
plugins_dir: _theme/_plugins

sass:
  style: compressed
  load_paths:
    - _theme/_sass
