# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaustav Das Modak
email: kaustav.dasmodak@gmail.com
description: "Kaustav's journal. An anecdote on research, programming, philosophy and what not."
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en_GB"
url: "https://kaustavdm.in" # the base hostname & protocol for your site
author:
  name: Kaustav Das Modak
  image: /assets/images/kido.jpg
  twitter: kaustavdm
twitter:
  username: kaustavdm
github:
  username: kaustavdm
social:
  name: Kaustav Das Modak
  links:
    - https://github.com/kaustavdm
    - http://twitter.com/kaustavdm
    - https://www.linkedin.com/in/kaustavdm
    - https://facebook.com/kaustavdm

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
markdown: kramdown

kramdown:
  input: GFM

timezone: Asia/Kolkata

permalink: :slug.html

# Paginate
paginate: 7
paginate_path: "/page-:num/"

# Exclude
exclude: [scripts/, README.md, Gemfile, Gemfile.lock, vendor]

# Safe mode
safe: true

# Feed
feed:
  path: atom.xml

layouts_dir: _theme/_layouts
data_dir: _theme/_data
includes_dir: _theme/_includes
plugins_dir: _theme/_plugins

sass:
  style: compressed
  load_paths:
    - _theme/_sass

collections:
  tagslist:
    output: true
    permalink: /tag/:slug

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: tagslist
    values:
      layout: tag
