# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaustav Das Modak
email: kaustav.dasmodak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kaustav's blog. An anecdote on research, photography, philosophy and what not.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaustavdm.in" # the base hostname & protocol for your site
twitter_username: kaustavdm
github_username:  kaustavdm

gems: [jekyll-paginate]

# Build settings
markdown: kramdown

timezone: Asia/Kolkata

permalink: /:year/:month/:slug.html

paginate: 7

paginate_path: "/page-:num/"

exclude: [scripts/, README.md, Gemfile, Gemfile.lock]
